name: Unity CI/CD Development Build

on: [workflow_dispatch]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  checkLicense:
    name: Check for the Unity license
    runs-on: ubuntu-latest
    steps:
      - name: Fail - No license
        if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
        run: exit 1

  build:    
    name: Build for ${{ matrix.targetPlatform}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows   # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneOSX
        projectPath: 
          - Descension
        customImage: 
          - unityci/editor:2020.3.26f1-base-0
        buildName: 
          - Descension
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true      

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |            
            Library-
            
      - uses: game-ci/unity-builder@v2
        env: 
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: auto
          allowDirtyBuild: true
          targetPlatform: ${{ matrix.targetPlatform }}          
          # customImage: ${{ matrix.customImage }}          
          projectPath: ${{ matrix.projectPath }}
          buildsPath: ${{ matrix.buildsPath }}
          buildName: ${{ matrix.buildName }}
          customParameters: -Development

      - uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
